---

# retro
game: HotWheelsStuntTrackChallenge-gba
state: Dinosaur_Boneyard_multi
scenario:

# model:
total_steps: 20_000_000
num_envs: 5
resume: False
model_load_path:
run_id:
model_save_freq: 50_000
model_save_path: ./models/
best_model_save_path: ./best_models/
gdrive_model_save_path:
gdrive_best_model_save_path:
# parameters:
policy: CnnPolicy
learning_rate: # lambda f: f * 2.5e-4
n_steps: 128
batch_size: 32
n_epochs: 4
gamma: 0.99
gae_lambda: 0.95
clip_range: 0.1
ent_coef: 0.01

# env / wrappers
action_space:
  - []
  - ["A"]
  - ["UP"]
  - ["DOWN"]
  - ["LEFT"]
  - ["RIGHT"]
  - ["L", "R"]
frame_skip: 4
frame_skip_prob: 0.25
terminate_on_crash: True
terminate_on_crash_reward: -5
terminate_on_wall_crash: True
terminate_on_wall_crash_reward: -5
use_deepmind_env: True
max_episode_steps: 5_100
frame_stack: 4
trim_obs: False
minimap_obs: False

# evaluation:
evaluation_statename: Dinosaur_Boneyard_multi
training_states:
  - Dinosaur_Boneyard_multi_71
  - Dinosaur_Boneyard_multi_156
  - Dinosaur_Boneyard_multi_180
  - Dinosaur_Boneyard_multi_290
  - Dinosaur_Boneyard_multi
eval_freq: 200_000
render_eval: False

# misc:
skip_wandb: False
file: