name: Build and publish linux wheel

on:
  push:
    branches: main

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ubuntu-latest  # todo, add more OS systems to see if they work as well
    strategy:
      matrix:
        python-version: ['3.10']  # '3.11'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install git cmake capnproto zlib1g-dev g++ build-essential python3-dev python3-pip pkg-config libzip-dev software-properties-common libbz2-dev

      - name: Install pip packages
        run: |
          python -m pip install --upgrade pip cmake wheel setuptools

      - name: Clone retro
        run: git clone https://github.com/zbeucler2018/stable-retro.git stable-retro

      - name: Build wheel
        run: |
          cd /home/runner/work/HotWheelsRL/HotWheelsRL/stable-retro/
          python_header_path=$(python3-config --cflags | awk -F '-I' '{print $2}' | awk '{print $1}')
          cmake . -DBUILD_TESTS=ON -DBUILD_MANYLINUX=ON -DPYTHON_INCLUDE_DIR=$python_header_path
          python setup.py -q build_ext -i -j3
          make -j3
          python setup.py bdist_wheel

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: t/home/runner/work/HotWheelsRL/HotWheelsRLstable-retro/dist/stable_retro-0.9.0-cp310-cp310-linux_x86_64.whl
          asset_name: stable_retro-0.9.0-cp310-cp310-linux_x86_64.whl
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"